function SoundResources() {}

SoundResources.sounds = {
    "waitingRoom1": new Audio("Resources/Audio/Music/waitingroom_music1.mp3"),
    "waitingRoom2": new Audio("Resources/Audio/Music/waitingroom_music2.mp3"),
    "titleMusic": new Audio("Resources/Audio/Music/title_music.mp3"),
    "researchMusic": new Audio("Resources/Audio/Music/research_music.mp3"),
    "inmemoriamMusic": new Audio("Resources/Audio/Music/inmemoriam_music.mp3"),
    
    "click": new Audio("Resources/Audio/UI Sounds/select.mp3"),
    "tothemorg": new Audio("Resources/Audio/Additional VO/tothemorg.mp3"),
    "monstrous": new Audio("Resources/Audio/Additional VO/monstrous.mp3"),
    "monstrousAct": new Audio("Resources/Audio/Additional VO/monstrousact.mp3"),
    "nextMonster": new Audio("Resources/Audio/Additional VO/nextmonster.mp3"),
    "welcome": new Audio("Resources/Audio/Additional VO/welcome.mp3"),
    "choir" : new Audio("Resources/Audio/SFX/choir.mp3"),
    //"dragonCancer": new Audio("Resources/Audio/Monster VO/dragon_cancer.mp3"),
    //"dragonCold": new Audio("Resources/Audio/Monster VO/dragon_cold.mp3"),
    //"dragonCongestion": new Audio("Resources/Audio/Monster VO/dragon_congestion.mp3"),
    //"dragonCured": new Audio("Resources/Audio/Monster VO/dragon_cured.mp3"),
    //"vampireCold": new Audio("Resources/Audio/Monster VO/vampire_cold.mp3"),
    //"vampireCured": new Audio("Resources/Audio/Monster VO/vampire_cured.mp3"),
    //"vampireToothache": new Audio("Resources/Audio/Monster VO/vampire_toothache.mp3"),
    //"vampireBloodpoisoning": new Audio("Resources/Audio/Monster VO/vampire_bloodpoisoning.mp3"),
    //"werewolfCold": new Audio("Resources/Audio/Monster VO/werewolf_cold.mp3"),
    //"werewolfCured": new Audio("Resources/Audio/Monster VO/werewolf_cured.mp3"),
    //"werewolfHairloss": new Audio("Resources/Audio/Monster VO/werewolf_hairloss.mp3"),
    //"werewolfSilverpoisoning": new Audio("Resources/Audio/Monster VO/werewolf_silverpoisoning.mp3"),
    
    "paper": new Audio("Resources/Audio/SFX/paper.mp3"),
    "back": new Audio("Resources/Audio/UI Sounds/back.mp3"),
    "highlight": new Audio("Resources/Audio/UI Sounds/highlight.mp3"),
    "vampire" : {
	"cold" : new Audio("Resources/Audio/Monster VO/vampire_cold.mp3"),
	"bPoisoning" : new Audio("Resources/Audio/Monster VO/vampire_bloodpoisoning.mp3"),
	"toothache" : new Audio("Resources/Audio/Monster VO/vampire_toothache.mp3"),
        "cured" : new Audio("Resources/Audio/Monster VO/vampire_cured.mp3"),
        "death" : new Audio("Resources/Audio/Monster VO/vampire_death.mp3"),
    },
    "dragon" : {
	"cold" : new Audio("Resources/Audio/Monster VO/dragon_cold.mp3"),
	"congestion" : new Audio("Resources/Audio/Monster VO/dragon_congestion.mp3"),
	"cancer" : new Audio("Resources/Audio/Monster VO/dragon_cancer.mp3"),
        "cured" : new Audio("Resources/Audio/Monster VO/dragon_cured.mp3"),
        "death" : new Audio("Resources/Audio/Monster VO/dragon_death.mp3"),
    },
    "werewolf" : {
	"cold" : new Audio("Resources/Audio/Monster VO/werewolf_cold.mp3"),
	"hairLoss" : new Audio("Resources/Audio/Monster VO/werewolf_hairloss.mp3"),
	"sPoisoning" : new Audio("Resources/Audio/Monster VO/werewolf_silverpoisoning.mp3"),
        "cured" : new Audio("Resources/Audio/Monster VO/werewolf_cured.mp3"),
        "death" : new Audio("Resources/Audio/Monster VO/werewolf_death.mp3"),
    },
}